# Generated by Django 4.2.21 on 2025-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='servicios/', verbose_name='Icono / Fondo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('delay', models.CharField(default='0.1s', max_length=10, verbose_name='Data-wow-delay')),
                ('enlace', models.URLField(blank=True, verbose_name='URL de ‘Ver Más’')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
    ]
